language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - SYMFONY_VERSION='2.2.*'
  - SYMFONY_VERSION='2.3.*'
  - SYMFONY_VERSION='2.4.*'
  - SYMFONY_VERSION='2.5.*@dev'

matrix:
  allow_failures:
    - env: "SYMFONY_VERSION='2.5.*@dev'"
    - php: hhvm
  exclude:
    - php: hhvm
      env: SYMFONY_VERSION='2.2.*'
    - php: hhvm
      env: SYMFONY_VERSION='2.3.*'
    - php: hhvm
      env: SYMFONY_VERSION='2.5.*@dev'

before_script:
  - composer require --no-update symfony/symfony=$SYMFONY_VERSION
  - composer install --prefer-source
  - export PATH=./vendor/bin:$PATH

script:
  - phpspec run -f pretty
  - behat -fprogress
